name: CI
on:
  pull_request:
    branches:
      - '**'
    types:
      - opened
      - synchronize
      - reopened
      - closed
jobs:
  dump:
    name: Dump GitHub context
    runs-on: ubuntu-latest
    env:
      GITHUB_CONTEXT: ${{ toJson(github) }}
    steps:
      - run: |
          echo "$GITHUB_CONTEXT"
      - run: |
          echo "$GITHUB_SHA"
          echo "$GITHUB_REF"
          echo "$GITHUB_REPOSITORY"
      - run: |
          echo "${{ github.event.action }}"
          echo "${{ github.event.pull_request.merged }}"
          echo "${{ github.event.action != 'closed'}} ${{ (github.event.pull_request.merged && github.ref == 'main') }}"
          echo "${{ github.event.action != 'closed' && (github.event.pull_request.merged && github.ref == 'main') }}"
          echo "${{ github.ref }}"
          echo "${{ github.ref == 'main' }}"
